#![no_std]
#![no_main]

mod ble_state_led;

use rmk::macros::rmk_keyboard;

// Vial config is automatically generated by `build.rs`, according to `vial.json`
// Please put `vial.json` at your project's root
#[rmk_keyboard]
mod keyboard {
    use embassy_nrf::gpio::{Level, Output, OutputDrive};

    use crate::ble_state_led::BleStateLedController;

    #[controller(event)]
    fn ble_state_led_controller() {
        let pin = Output::new(p.P0_30, Level::Low, OutputDrive::Standard);
        BleStateLedController::new(pin)
    }
}
